# Generated by Django 6.0.4 on 2026-04-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatDeteksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasien', models.CharField(max_length=100)),
                ('tanggal_tes', models.DateTimeField(auto_now_add=True)),
                ('smoking', models.IntegerField()),
                ('mental_stress', models.IntegerField()),
                ('exposure_to_pollution', models.IntegerField()),
                ('energy_level', models.IntegerField()),
                ('immune_weakness', models.IntegerField()),
                ('breathing_issue', models.IntegerField()),
                ('throat_discomfort', models.IntegerField()),
                ('family_history', models.IntegerField()),
                ('smoking_family_history', models.IntegerField()),
                ('stress_immune', models.IntegerField()),
                ('hasil_prediksi', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
